from scraper.selectors import CSSSingleSelector, CSSMultiSelector
from scraper.extractors import HTMLValueExtractor

from .models import FieldConfig, ParserConfig, DataConfig


config = ParserConfig(
    url_template='https://scraping-interview.onrender.com/mock_indemnity/<customerId>',
    multipage=False,
    data=[
        DataConfig(
            name='agent',
            container_selector=CSSSingleSelector('.agent-detail'),
            fields=[
                FieldConfig(
                    name='name',
                    selector=CSSSingleSelector('.value-name'),
                    extractor=HTMLValueExtractor(),
                ),
                FieldConfig(
                    name='producer_code',
                    selector=CSSSingleSelector('.value-producerCode'),
                    extractor=HTMLValueExtractor(),
                ),
                FieldConfig(
                    name='agency_name',
                    selector=CSSSingleSelector('.value-agencyName'),
                    extractor=HTMLValueExtractor(),
                ),
                FieldConfig(
                    name='agency_code',
                    selector=CSSSingleSelector('.value-agencyCode'),
                    extractor=HTMLValueExtractor(),
                ),
            ]
        ),
        DataConfig(
            name='customer',
            container_selector=CSSSingleSelector('.customer-detail'),
            fields=[
                FieldConfig(
                    name='id',
                    selector=CSSSingleSelector('.value-id'),
                    extractor=HTMLValueExtractor(),
                ),
                FieldConfig(
                    name='name',
                    selector=CSSSingleSelector('.value-name'),
                    extractor=HTMLValueExtractor(),
                ),
                FieldConfig(
                    name='email',
                    selector=CSSSingleSelector('.value-email'),
                    extractor=HTMLValueExtractor(),
                ),
                FieldConfig(
                    name='address',
                    selector=CSSSingleSelector('.value-address'),
                    extractor=HTMLValueExtractor(),
                ),
            ]
        ),
        DataConfig(
            name='policy',
            container_selector=CSSMultiSelector('#policy-list .list-group-item'),
            array=True,
            fields=[
                FieldConfig(
                    name='id',
                    selector=CSSSingleSelector('.id'),
                    extractor=HTMLValueExtractor(),
                ),
                FieldConfig(
                    name='premium',
                    selector=CSSSingleSelector('.premium'),
                    extractor=HTMLValueExtractor(),
                ),
                FieldConfig(
                    name='status',
                    selector=CSSSingleSelector('.status'),
                    extractor=HTMLValueExtractor(),
                ),
                FieldConfig(
                    name='effective_date',
                    selector=CSSSingleSelector('.effectiveDate'),
                    extractor=HTMLValueExtractor(),
                ),
                FieldConfig(
                    name='termination_date',
                    selector=CSSSingleSelector('.terminationDate'),
                    extractor=HTMLValueExtractor(),
                ),
                FieldConfig(
                    name='last_payment_date',
                    selector=CSSSingleSelector('.lastPaymentDate'),
                    extractor=HTMLValueExtractor(),
                ),
            ]
        ),
    ]
)
